### ISSUE TITLE
Occasionally, starting app appears to not open

### ISSUE THREAD

**Issue by psionprime** [miragedmuk/ARKViewer-Master#3]
It does open, just off screen. The config file has window X/Y  = -32000 when this happens. Manual editing the config to , eg., 100,100 brings the window to the main desktop though it needs manually resized to be useful again.

**Comment by miragedmuk** [comment]
Caused by closing application when the app was minimized.  Have updated code to only save screen co ordinates and size if the window state is NORMAL.  No screen location / size information will be saved if Minimized/Maximized.

**Comment by psionprime** [comment]
Ooooooo fast response =) very cool
